# Generated by Django 5.1.2 on 2024-10-23 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="chat_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
